export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const GET_TRANSACTION = "GET_TRANSACTION";
export const LOAD_TRANSACTIONS = "LOAD_TRANSACTIONS";
export const TRANSACTION_ACCEPTED_NOT_FUNDED =
  "TRANSACTION_ACCEPTED_NOT_FUNDED";
export const REJECT_DELIVERED_TRANSACTION = "REJECT_DELIVERED_TRANSACTION";
export const TRANSACTION_DELIVERED = "TRANSACTION_DELIVERED";
export const TRANSACTION_IN_PROGRESS = "TRANSACTION_IN_PROGRESS";
export const TRANSACTION_REQUEST_REJECTED = "TRANSACTION_REQUEST_REJECTED";
export const BUYER_CONFIRM_DELIEVERED_TRANSACTION =
  "BUYER_CONFIRM_DELIEVERED_TRANSACTION";
export const AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION";
export const ACCEPTED_AND_FUNDED = "ACCEPTED_AND_FUNDED";
export const TRANSACTION_ERROR = "TRANSACTION_ERROR";
export const CLEAR_FIELDS = "CLEAR_FIELDS";
export const ADD_DISPUTE = "ADD_DISPUTE";
export const LOAD_DISPUTES = "LOAD_DISPUTES";
export const GET_DISPUTE = "GET_DISPUTE";
